---
- name: add safeeyes repo
  ansible.builtin.apt_repository:
    repo: ppa:slgobinath/safeeyes

- name: install packages
  apt:
    name:
      - audacity
      - easytag
      - curl
      - git
      - gnome-calculator
      - gparted
      - html-xml-utils
      - htop
      - inkscape
      - keepassx
      - liferea
      - light-locker
      - meld
      - p7zip
      - safeeyes
      - vim
      - vlc
      - wireshark
    state: latest
    update_cache: "yes"

- name: skypeforlinux_installed
  command: dpkg-query -W skypeforlinux
  register: skypeforlinux_installed
  failed_when: skypeforlinux_installed.rc > 1

- name: skypeforlinux
  apt:
    deb: 'https://repo.skype.com/latest/skypeforlinux-64.deb'
  when: skypeforlinux_installed.rc == 1

- name: code_installed
  command: dpkg-query -W code
  register: code_installed
  failed_when: code_installed.rc > 1

- name: code
  apt:
    deb: 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'
  when: code_installed.rc == 1

- name: zoom_installed
  command: dpkg-query -W zoom
  register: zoom_installed
  failed_when: zoom_installed.rc > 1

- name: zoom
  apt:
    deb: 'https://zoom.us/client/latest/zoom_amd64.deb'
  when: zoom_installed.rc == 1

- name: teamviewer_installed
  command: dpkg-query -W teamviewer
  register: teamviewer_installed
  failed_when: teamviewer_installed.rc > 1

- name: teamviewer
  apt:
    deb: 'https://zoom.us/client/latest/zoom_amd64.deb'
  when: teamviewer_installed.rc == 1


- name: purge packages
  apt:
    name:
      - pidgin
      - thunderbird
      - transmission-gtk
    purge: yes
    state: absent

- name: update locales
  ansible.builtin.command: >
    update-locale LANG=en_US.UTF-8
    LC_NUMERIC=en_US.UTF-8
    LC_TIME=en_US.UTF-8
    LC_MONETARY=en_US.UTF-8
    LC_PAPER=en_US.UTF-8
    LC_NAME=en_US.UTF-8
    LC_ADDRESS=en_US.UTF-8
    LC_TELEPHONE=en_US.UTF-8
    LC_MEASUREMENT=en_US.UTF-8
    LC_IDENTIFICATION=en_US.UTF-8
