- name: Configure xcfe4
  ansible.builtin.script: xfconf-query.sh

- name: Configure xfce4-terminal
  copy:
    src: terminalrc
    dest: ~/.config/xfce4/terminal/terminalrc
    backup: yes
    mode: 0664

- name: Create safeeyes directory (if it does not exist)
  ansible.builtin.file:
    path: ~/.config/safeeyes
    state: directory
    mode: 0755

- name: Configure safeeyes
  copy:
    src: safeeyes.json
    dest: ~/.config/safeeyes/safeeyes.json
    backup: yes
    mode: 0664

- name: Create keepassx2 directory (if it does not exist)
  ansible.builtin.file:
    path: ~/.config/keepassx
    state: directory
    mode: 0755

- name: Configure keepassx2
  copy:
    src: keepassx2.ini
    dest: ~/.config/keepassx/keepassx2.ini
    backup: yes
    mode: 0664

- name: Configure git
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    backup: yes
    mode: 0664

# https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
- name: Configure git prompt
  copy:
    src: git-prompt.sh
    dest: ~/.git-prompt.sh
    backup: yes
    mode: 0664

- name: Configure bash prompt
  copy:
    src: .bash-prompt.sh
    dest: ~/.bash-prompt.sh
    backup: yes
    mode: 0664

- name: Configure bashrc
  copy:
    src: .bashrc
    dest: ~/.bashrc
    backup: yes
    mode: 0664