- name: Configure xcfe4
  ansible.builtin.script: xfconf-query.sh

- name: Configure xfce4-terminal
  copy:
    src: terminalrc
    dest: ~/.config/xfce4/terminal/terminalrc
    backup: yes
    mode: 0664

- name: Configure safeeyes
  copy:
    src: safeeyes.json
    dest: ~/.config/safeeyes/safeeyes.json
    backup: yes
    mode: 0664

- name: Configure keepassx2
  copy:
    src: keepassx2.ini
    dest: ~/.config/keepassx/keepassx2.ini
    backup: yes
    mode: 0664
