- name: Configure xcfe4
  ansible.builtin.script: xfconf-query.sh

- name: Configure xfce4-terminal
  copy:
    src: terminalrc
    dest: ~/.config/xfce4/terminal/terminalrc
    backup: yes
    mode: 0664
