- name: restic_installed
  command: which restic
  register: restic_installed
  failed_when: restic_installed.rc > 1

- name: Download restic
  get_url:
    url: https://github.com/restic/restic/releases/download/v0.12.0/restic_0.12.0_linux_amd64.bz2
    dest: /tmp/restic.bz2
    checksum: sha256:63d13d53834ea8aa4d461f0bfe32a89c70ec47e239b91f029ed10bd88b8f4b80
  when: restic_installed.rc == 1

- name: Install restic
  ansible.builtin.script: install-restic.sh
  when: restic_installed.rc == 1